# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  stop_on_error = true

[log]
  time = true

[color]
  main = "cyan"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
