# 使用するGoのバージョンを指定
FROM golang:1.21.3 AS builder

# ワーキングディレクトリの設定
WORKDIR /app

# 依存関係をインストール
COPY go.mod .
COPY go.sum .
RUN go mod download

# ソースコードをコピー
COPY . .

# アプリケーションをビルド
RUN CGO_ENABLED=0 GOOS=linux go build -o /myapi ./cmd/myapi

# 実行用の軽量なベースイメージを使用
FROM alpine:latest
RUN apk --no-cache add ca-certificates

# ビルダーステージからビルドしたバイナリをコピー
COPY --from=builder /myapi /myapi

# ポートを公開
EXPOSE 8080

# アプリケーションを実行
CMD ["/myapi"]
