version: '3'
services:
  app:
    container_name: app1-go
    build:
      context: .
      dockerfile: Dockerfile.Go
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: app1-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: