# 使用するGoのバージョンを指定
FROM golang:1.21.3 AS builder

# ワーキングディレクトリの設定
WORKDIR /app

# 依存関係をインストール
COPY go.mod .
COPY go.sum .
RUN go mod download

# ソースコードをコピー
COPY . .

# アプリケーションをビルド
RUN CGO_ENABLED=0 GOOS=linux go build -o /app1-be ./cmd/myapi